services:
  - type: web
    name: pest-prediction-api
    runtime: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    rootDir: backend
